services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: resume-builder-db

    environment:
      POSTGRES_DB: resumebuilder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: