spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resumebuilder
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: false
  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        options:
          model: qwen3

      embedding:
        options:
          model: nomic-embed-text

logging:
  level:
    org.hibernate.SQL: DEBUG
    # org.hibernate.orm.jdbc.bind: TRACE